[package]
name = "diffopt"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "diffopt"
path = "src/lib.rs"

[dependencies]
rand = "*"
arraydiff = { path = "../arraydiff" }
densearray = "*"
devicemem_cuda = { path = "../libdevicemem_cuda" }
